// Generated by scripts/hold-manifest.mjs — do not edit by hand.
// Stills of the places that are real and not finished, keyed by the slug
// in HOLD. A place with no entry here simply has no picture yet.

export const HOLD_STILLS: Record<string, string> = {

};
