// Generated by scripts/sticker-manifest.mjs — do not edit by hand.
// The pack under public/stickers/full, in numeric order, which is the
// order they sit in on Telegram. The label is the file name.

export type Sticker = { id: string; label: string; full: string; thumb: string };

export const STICKERS: Sticker[] = [
  { id: '01-gm', label: 'gm', full: '/stickers/full/01-gm.png', thumb: '/stickers/thumb/01-gm.png' },
  { id: '02-gn', label: 'gn', full: '/stickers/full/02-gn.png', thumb: '/stickers/thumb/02-gn.png' },
  { id: '03-wagmi', label: 'wagmi', full: '/stickers/full/03-wagmi.png', thumb: '/stickers/thumb/03-wagmi.png' },
  { id: '04-ngmi', label: 'ngmi', full: '/stickers/full/04-ngmi.png', thumb: '/stickers/thumb/04-ngmi.png' },
  { id: '05-paste-it', label: 'paste it', full: '/stickers/full/05-paste-it.png', thumb: '/stickers/thumb/05-paste-it.png' },
  { id: '06-reading', label: 'reading', full: '/stickers/full/06-reading.png', thumb: '/stickers/thumb/06-reading.png' },
  { id: '07-no', label: 'no', full: '/stickers/full/07-no.png', thumb: '/stickers/thumb/07-no.png' },
  { id: '08-it-can-be-changed-beneath-you', label: 'it can be changed beneath you', full: '/stickers/full/08-it-can-be-changed-beneath-you.png', thumb: '/stickers/thumb/08-it-can-be-changed-beneath-you.png' },
  { id: '09-brb', label: 'brb', full: '/stickers/full/09-brb.png', thumb: '/stickers/thumb/09-brb.png' },
  { id: '10-still-here', label: 'still here', full: '/stickers/full/10-still-here.png', thumb: '/stickers/thumb/10-still-here.png' },
  { id: '11-forty-characters', label: 'forty characters', full: '/stickers/full/11-forty-characters.png', thumb: '/stickers/thumb/11-forty-characters.png' },
  { id: '12-cursed-otherwise-fine', label: 'cursed otherwise fine', full: '/stickers/full/12-cursed-otherwise-fine.png', thumb: '/stickers/thumb/12-cursed-otherwise-fine.png' },
  { id: '13-the-candle', label: 'the candle', full: '/stickers/full/13-the-candle.png', thumb: '/stickers/thumb/13-the-candle.png' },
  { id: '14-the-raven', label: 'the raven', full: '/stickers/full/14-the-raven.png', thumb: '/stickers/thumb/14-the-raven.png' },
  { id: '15-shut', label: 'shut', full: '/stickers/full/15-shut.png', thumb: '/stickers/thumb/15-shut.png' },
  { id: '16-night-one', label: 'night one', full: '/stickers/full/16-night-one.png', thumb: '/stickers/thumb/16-night-one.png' },
  { id: '17-i-counted', label: 'i counted', full: '/stickers/full/17-i-counted.png', thumb: '/stickers/thumb/17-i-counted.png' },
  { id: '18-oh', label: 'oh', full: '/stickers/full/18-oh.png', thumb: '/stickers/thumb/18-oh.png' },
  { id: '19-the-stone-says', label: 'the stone says', full: '/stickers/full/19-the-stone-says.png', thumb: '/stickers/thumb/19-the-stone-says.png' },
  { id: '20-gg', label: 'gg', full: '/stickers/full/20-gg.png', thumb: '/stickers/thumb/20-gg.png' },
];

/** Where the pack is installed from. */
export const STICKER_PACK = 'https://t.me/addstickers/HollowAgent';
