// Generated by scripts/wallpaper-manifest.mjs — do not edit by hand.
// Everything under public/wallpapers/full, in name order. Adding a
// wallpaper is a file copy: this list is rebuilt on every dev start and
// every build, so it cannot disagree with the folder.

export type Wallpaper = {
  id: string;
  /** Full-size image, what a click opens and what a save writes. */
  full: string;
  /** Grid image. Falls back to the full one when no thumbnail exists. */
  thumb: string;
  w: number;
  h: number;
};

export const WALLPAPERS: Wallpaper[] = [
  { id: 'hollow-01', full: '/wallpapers/full/hollow-01.jpg', thumb: '/wallpapers/thumb/hollow-01.jpg', w: 1672, h: 941 },
  { id: 'hollow-02', full: '/wallpapers/full/hollow-02.jpg', thumb: '/wallpapers/thumb/hollow-02.jpg', w: 1672, h: 941 },
  { id: 'hollow-03', full: '/wallpapers/full/hollow-03.jpg', thumb: '/wallpapers/thumb/hollow-03.jpg', w: 1672, h: 941 },
  { id: 'hollow-04', full: '/wallpapers/full/hollow-04.jpg', thumb: '/wallpapers/thumb/hollow-04.jpg', w: 1672, h: 941 },
  { id: 'hollow-05', full: '/wallpapers/full/hollow-05.jpg', thumb: '/wallpapers/thumb/hollow-05.jpg', w: 1672, h: 941 },
  { id: 'hollow-06', full: '/wallpapers/full/hollow-06.jpg', thumb: '/wallpapers/thumb/hollow-06.jpg', w: 1672, h: 941 },
  { id: 'hollow-07', full: '/wallpapers/full/hollow-07.jpg', thumb: '/wallpapers/thumb/hollow-07.jpg', w: 1672, h: 941 },
  { id: 'hollow-08', full: '/wallpapers/full/hollow-08.jpg', thumb: '/wallpapers/thumb/hollow-08.jpg', w: 1672, h: 941 },
  { id: 'hollow-09', full: '/wallpapers/full/hollow-09.jpg', thumb: '/wallpapers/thumb/hollow-09.jpg', w: 1672, h: 941 },
  { id: 'hollow-10', full: '/wallpapers/full/hollow-10.jpg', thumb: '/wallpapers/thumb/hollow-10.jpg', w: 1672, h: 941 },
  { id: 'hollow-11', full: '/wallpapers/full/hollow-11.jpg', thumb: '/wallpapers/thumb/hollow-11.jpg', w: 1672, h: 941 },
  { id: 'hollow-12', full: '/wallpapers/full/hollow-12.jpg', thumb: '/wallpapers/thumb/hollow-12.jpg', w: 1672, h: 941 },
  { id: 'hollow-13', full: '/wallpapers/full/hollow-13.jpg', thumb: '/wallpapers/thumb/hollow-13.jpg', w: 1672, h: 941 },
  { id: 'hollow-14', full: '/wallpapers/full/hollow-14.jpg', thumb: '/wallpapers/thumb/hollow-14.jpg', w: 1672, h: 941 },
  { id: 'hollow-15', full: '/wallpapers/full/hollow-15.jpg', thumb: '/wallpapers/thumb/hollow-15.jpg', w: 1672, h: 941 },
  { id: 'hollow-16', full: '/wallpapers/full/hollow-16.jpg', thumb: '/wallpapers/thumb/hollow-16.jpg', w: 1672, h: 941 },
  { id: 'hollow-17', full: '/wallpapers/full/hollow-17.jpg', thumb: '/wallpapers/thumb/hollow-17.jpg', w: 1672, h: 941 },
  { id: 'hollow-18', full: '/wallpapers/full/hollow-18.jpg', thumb: '/wallpapers/thumb/hollow-18.jpg', w: 1672, h: 941 },
  { id: 'hollow-19', full: '/wallpapers/full/hollow-19.jpg', thumb: '/wallpapers/thumb/hollow-19.jpg', w: 1672, h: 941 },
];
